CREATE TABLE notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_event_id UUID          NOT NULL UNIQUE,
    user_id         BIGINT        NOT NULL,
    order_id        BIGINT        NOT NULL,
    type            VARCHAR(30)   NOT NULL,
    title           VARCHAR(255)  NOT NULL,
    message         VARCHAR(1000) NOT NULL,
    is_read         BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_notifications_user ON notifications (user_id, created_at DESC);
