CREATE TABLE payments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT         NOT NULL UNIQUE,
    user_id         BIGINT         NOT NULL,
    amount          NUMERIC(12, 2) NOT NULL,
    status          VARCHAR(20)    NOT NULL,
    transaction_ref VARCHAR(40),
    failure_reason  VARCHAR(500),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_payments_user ON payments (user_id, created_at DESC);
