CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku         VARCHAR(40)    NOT NULL UNIQUE,
    name        VARCHAR(255)   NOT NULL,
    description VARCHAR(2000),
    category    VARCHAR(60)    NOT NULL,
    price       NUMERIC(12, 2) NOT NULL CHECK (price > 0),
    image_url   VARCHAR(255),
    active      BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Speeds up "WHERE category = ?" filtering.
CREATE INDEX idx_products_category ON products (category);
