CREATE TABLE inventory_items (
    product_id         BIGINT PRIMARY KEY,
    sku                VARCHAR(40) NOT NULL,
    available_quantity INT NOT NULL CHECK (available_quantity >= 0),
    reserved_quantity  INT NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
    updated_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE stock_reservations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT NOT NULL UNIQUE,
    status     VARCHAR(20) NOT NULL,
    reason     VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE stock_reservation_lines (
    reservation_id BIGINT NOT NULL REFERENCES stock_reservations (id) ON DELETE CASCADE,
    product_id     BIGINT NOT NULL,
    quantity       INT NOT NULL CHECK (quantity > 0)
);

CREATE INDEX idx_reservation_lines_reservation ON stock_reservation_lines (reservation_id);
